### PR TITLE
Update wog graphic fix to v2.19

### PR DESCRIPTION
**Pull request by krs0**

### CODE REVIEW

**Comment by DjWarmonger** [comment]
I think new sawmill replacing the old one is controversial: 
image

**Comment by krs0** [comment]
I just saw it also on dirt... looks ugly :(.
But... that's the mod :)
In my compilation I will undo this change.

**Comment by krs0** [comment]
I am surprised that the new dirt trees do not appear? at all? Is it related to biomes?

**Comment by DjWarmonger** [comment]
Yes, only objects listed in biomes appear.

**Comment by DjWarmonger** [comment]
Also, Mirror of The Home-Way looks just like Town Gate, that's confusing.
New Mirror of The Home-Way

**Comment by DjWarmonger** [comment]
Suprisingly, I found the classic one on snow, with same mod active:
image

**Pull request merged**
