### PR TITLE
Fix the edges of the WOG campaign button

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

This PR fixes the edges of the WOG campaign button. The wing of the dragon moves when your mouse is over the button.

PS: If the problem is still on the extension, would it be possible to contact them and suggest the `.def` file?

### CODE REVIEW

**Comment by Olegmods** [comment]
> Hi @misiokles,
> 
> This PR fixes the edges of the WOG campaign button. The wing of the dragon moves when your mouse is over the button.
> 
> PS: If the problem is still on the extension, would it be possible to contact them and suggest the `.def` file?

I guess ERA doesn't use the WoG campaign button. And original WoG isn't developed now.

**Comment by misiokles** [comment]
Contact with who?

**Comment by Fabrice-TIERCELIN** [comment]
OK so we contact nobody from WoG.

@misiokles, can we get in touch with the creators of _Day of Rekoning_? It would be great to do the dubbing or show how to dub before the release 🤩

**Comment by misiokles** [comment]
WoG was made 15-20 years ago. I guess none of the original creators is 'in game'..

And I don't have contact with DoR team.

**Comment by Olegmods** [comment]
> OK so we contact nobody from WoG.
> 
> @misiokles, can we get in touch with the creators of _Day of Rekoning_? It would be great to do the dubbing or show how to dub before the release 🤩

In theory, you can help DoR team with translations. But I guess you will need some contacts of team members. Many of them are on Discord AFAIK.

**Comment by Fabrice-TIERCELIN** [comment]
So can it be merged? WoG don't need to be maintained to have the content fixed. I need this merge for another contribution.

**Comment by misiokles** [comment]
I guess it's better wait with merging - maybe it will be possible to choose multiple addons campaings screens like WoG/Hota/Chronicles/DoR/Antagarich Burning and maybe more.

**Comment by Olegmods** [comment]
I think that the better idea would be a SoD campaign button for the theme and a submod with WoG campaigns (and a new button) later. Since SoD campaigns are the "WoG campaigns" now and WoG button may confuse people. I found SoD button for WoG menu in one ERA mod, but the icon text in Russian.

**Comment by GeorgeK1ng** [comment]
This could be merged I quess, it just improve current button in same logic.
image

**Pull request merged**
