### PR TITLE
Magic mushrooms

### PR DESCRIPTION
**Pull request by DjWarmonger**

### CODE REVIEW

**Comment by rilian-la-te** [comment]
@DjWarmonger there is no SECONDARY_SKILL_PREMY in 1.2) Please, replace to working bonuses)

**Comment by DjWarmonger** [comment]
> @DjWarmonger there is no SECONDARY_SKILL_PREMY in 1.2) Please, replace to working bonuses)

It uses `MAGIC_SCHOOL_SKILL`, no changes here as far as I see?

**Comment by misiokles** [comment]
In vcmi-1.2 branch there's versiom compatible with 1.2.

**Comment by DjWarmonger** [comment]
So this PR should be already closed?

**Comment by misiokles** [comment]
Yws

**Comment by rilian-la-te** [comment]
Look to sphinx and learning)

**Pull request closed without merging**
